name: CI

on:
  pull_request:
    paths:
      - '.github/workflows/ci.yml'
      - 'package.json'
      - 'packages/**'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'
      - 'tsconfig.json'
      - 'vite.config.ts'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/ci.yml'
      - 'package.json'
      - 'packages/**'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'
      - 'tsconfig.json'
      - 'vite.config.ts'

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: voidzero-dev/setup-vp@v1
        with:
          cache: true
          node-version: '24'
      - run: vp install --frozen-lockfile
      - run: vp run -r pack
      - run: vp check
      - run: vp test
